### ISSUE TITLE
Executable name conflicts with borg backup utility

### ISSUE THREAD

**Issue by faithanalog** [ok-borg/borg#1]
https://github.com/borgbackup/borg also uses the "borg" command, and is already present in several linux distributions including Arch, Debian, and Ubuntu. Given its popularity, I might suggest modifying the executable name somewhat to avoid conflict with it.

**Comment by crufter** [comment]
This is a completely valid point, as an Ubuntu user (on servers) I never encountered borg, but I realise this may be an issue.

I will think about a name change or an other solution, meanwhile I suggest just changing the exec name if you already have the other borg installed - it won't affect anything, since the borg client is just a tiny self contained library, it absolutely does not care about its name.
