### ISSUE TITLE
Pick an unique name

### ISSUE THREAD

**Issue by ghost** [ok-borg/borg#16]
The name "borg" is already used by a more significant free software project.[1](http://borgbackup.readthedocs.io/en/stable/)

Is it really that hard to type your name idea to a search engine to see if it has already been used by someone else?

**Comment by jeremyletang** [comment]
Is it really that hard to be polite when you speak with people ?

**Comment by J00MZ** [comment]
The above attitude aside, I actually was wondering about the name too - Google's [Kubernetes](https://github.com/kubernetes/kubernetes) predecessor was (and still is) named Borg, see [this](https://www.quora.com/Does-Google-use-the-Open-Source-Kubernetes-or-a-version-of-Borg-for-their-own-container-management) question.

**Comment by crufter** [comment]
@Tsutsukakushi It is not that hard. I am truly sorry that this name collision disturbed you, however same names are being used for a lot of projects, there is Google's Borg as well.

**Comment by crufter** [comment]
@J00MZ The reason it collides because I have not expected people to pick this up at all - I hacked it together in a day or so and didn't think much about the name - I knew about the other borgs, but I liked the name for a search engine like thingy - it just seems fitting, putting knowledge in a "collective mind" and then querying it.

I pretty much expected this project project to sit amongst my other unknown github repos - and people don't complain about name collisions if they don't know about your project.

**Comment by ghost** [comment]
> however same names are being used for a lot of projects

Yes and this is very annoying.

**Comment by crufter** [comment]
@Tsutsukakushi I understand your frustration but it's really easy to get around, it's a single binary, it's not like installation requires you to create 10k subfolders all over your system.

 Once I find a name I like more I might change it.

**Comment by ghost** [comment]
The major part of the problem is with discoverabilitity through search engines and package managers.
